// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CP.Shared.Test.Compensation.CompensationCalculation
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CompensationCalculationService. GetForCompensations")]
    public partial class CompensationCalculationService_GetForCompensationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GetForCompensations.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CompensationCalculationService. GetForCompensations", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 2
#line 3
 testRunner.Given("Requestor is going to calculate compensations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "USD"});
            table1.AddRow(new string[] {
                        "EUR"});
            table1.AddRow(new string[] {
                        "BYR"});
#line 4
 testRunner.And("Currencies are customized to have properties", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All USD compensations")]
        public virtual void AllUSDCompensations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All USD compensations", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 2
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value",
                        "Currency",
                        "PromotionType",
                        "ApplyDate",
                        "SalaryType"});
            table2.AddRow(new string[] {
                        "Salary_1",
                        "100",
                        "USD",
                        "Salary",
                        "2018-05-02",
                        "Monthly"});
#line 11
 testRunner.Given("Salaries are customized to have properties", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value",
                        "Currency",
                        "PromotionType",
                        "ApplyDate"});
            table3.AddRow(new string[] {
                        "Bonus_1",
                        "300",
                        "USD",
                        "Bonus",
                        "2018-04-02"});
#line 14
 testRunner.And("Bonuses are customized to have properties", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Currency",
                        "Ratio",
                        "Type",
                        "Date"});
            table4.AddRow(new string[] {
                        "USD",
                        "1.0",
                        "Daily",
                        "2018-05-02"});
#line 17
 testRunner.And("CurrencyRates are customized to have properties", ((string)(null)), table4, "And ");
#line 20
 testRunner.When("Calculate compensations is requested", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("Total value should be 1500", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.And("Result currency should be USD", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple currencies")]
        public virtual void MultipleCurrencies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple currencies", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 2
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value",
                        "Currency",
                        "PromotionType",
                        "ApplyDate",
                        "SalaryType"});
            table5.AddRow(new string[] {
                        "Salary_1",
                        "100",
                        "USD",
                        "Salary",
                        "2018-05-02",
                        "Monthly"});
            table5.AddRow(new string[] {
                        "Salary_2",
                        "100",
                        "BYR",
                        "Salary",
                        "2018-04-02",
                        "Annual"});
            table5.AddRow(new string[] {
                        "Salary_3",
                        "100",
                        "EUR",
                        "Salary",
                        "2018-03-02",
                        "Annual"});
#line 25
 testRunner.Given("Salaries are customized to have properties", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value",
                        "Currency",
                        "PromotionType",
                        "ApplyDate"});
            table6.AddRow(new string[] {
                        "Bonus_1",
                        "300",
                        "USD",
                        "Bonus",
                        "2018-04-02"});
#line 30
 testRunner.And("Bonuses are customized to have properties", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Currency",
                        "Ratio",
                        "Type",
                        "Date"});
            table7.AddRow(new string[] {
                        "USD",
                        "1.0",
                        "Daily",
                        "2018-05-02"});
            table7.AddRow(new string[] {
                        "BYR",
                        "2.0",
                        "Daily",
                        "2018-05-02"});
            table7.AddRow(new string[] {
                        "EUR",
                        "1.25",
                        "Daily",
                        "2018-05-02"});
#line 33
 testRunner.And("CurrencyRates are customized to have properties", ((string)(null)), table7, "And ");
#line 38
 testRunner.When("Calculate compensations is requested", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("Total value should be 1630", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.And("Result currency should be USD", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
